version: "3.7"
services:
    redis:
        image: redis:7.0-alpine
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - redis-local:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
    api:
        build: ./api
        command: npm start
        ports:
            - "8001:8001"
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis

    ui:
        build: ./ui
        command: npm run dev -- --host
        ports:
            - "5173:5173"
        depends_on:
            - api

volumes:
    redis-local:
