FROM node:lts-hydrogen

RUN apt-get update

RUN apt-get install -y \
        build-essential \
        libcairo2-dev \
        libpango1.0-dev \
        libjpeg-dev \
        libgif-dev \
        librsvg2-dev \
        ;

WORKDIR /api

COPY . .

RUN npm install

RUN npm explore @tensorflow/tfjs-node -- npm run install-from-source
